# Generated by Django 5.1.6 on 2025-02-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='event_assign',
            field=models.ManyToManyField(related_name='participants', to='events.add_event_model'),
        ),
    ]
